### ISSUE TITLE
Adding new domain models

### ISSUE THREAD

**Issue by DanAtVeolia** [litestar-org/litestar-pg-redis-docker#198]
I've tried creating a books domain model to explore using this code as boilerplate for a larger application. Everything works (building app and testing endpoints manually) except I can't get the tests to pass for the _books_repository fixture that I've created. The test_authors tests now fail (except create):

tests/unit/controllers/test_authors.py::test_list_authors FAILED
tests/unit/controllers/test_authors.py::test_create_author PASSED
tests/unit/controllers/test_authors.py::test_get_author FAILED
tests/unit/controllers/test_authors.py::test_update_author FAILED
tests/unit/controllers/test_authors.py::test_delete_author FAILED

The raw books fixture has successfully been added to the mock repository collection (I've seen it in a log I created) but somehow the repository for books doesn't get tied to the test client.

I assume the monkeypatch and db session may be conflicting? Any advice?

**Comment by peterschutt** [comment]
Will need a bit more info to help you. Have you got a repo you can share? Or can you make a PR of your changes into this app?

**Comment by Goldziher** [comment]
this appears stale, closing. Feel free to reopen with more context
