### ISSUE TITLE
Discussion: why use SQLAlchemyInitPlugin and not SQLAlchemyPlugin

### ISSUE THREAD

**Issue by audiovention** [litestar-org/litestar-pg-redis-docker#279]
Is there a specific reason the example repo uses the SQLAlchemyInitPlugin instead of the SQLAlchemyPlugin, preventing sql model serialization?

**Comment by peterschutt** [comment]
> Is there a specific reason the example repo uses the SQLAlchemyInitPlugin instead of the SQLAlchemyPlugin, preventing sql model serialization?

We explicitly define the DTOs in the example repo, whereas the SQLAlchemyPlugin implicitly defines them where they aren't otherwise configured. So, just not needed.

**Comment by audiovention** [comment]
thanks, that clears it up. Maybe put a comment in the code for people wondering like me.

**Comment by peterschutt** [comment]
PRs welcome - we'd also welcome an example endpoint that doesn't explicitly define DTOs and leverages the serialization plugin. But I'll leave that to you if you're motivated. No probs if not! Thanks for reaching out.
